# ~/.config/kitty/kitty.conf

# --- Window ---
background_opacity 0.85

# --- Font ---
font_family AtkynsonMono Nerd Font
font_size 10.5

# --- Lesbian Pride Theme Colors ---
foreground            #fcf8f2
background            #2d111e
cursor                #ff9b55
cursor_text_color     #2d111e
selection_foreground  #2d111e
selection_background  #ff9b55

# --- Normal colors ---
color0  #2d111e
color1  #d52d00
color2  #ff9b55
color3  #e461a8
color4  #a50062
color5  #b84382
color6  #f4a172
color7  #fcf8f2

# --- Bright colors ---
color8  #4a2034
color9  #e64a19
color10 #ffb37e
color11 #f08cb4
color12 #c2185b
color13 #d86fa4
color14 #f7be9b
color15 #ffffff

# --- Cursor style ---
cursor_shape beam
cursor_blink_interval 0.5
