# ~/.config/kitty/kitty.conf

# --- Window ---
background_opacity 0.85

# --- Font ---
font_family Atkinson Hyperlegible Mono
font_size 10.5

# --- Colors ---
foreground #d8b4ff
background #241b2f

# Cursor
cursor #c084fc
cursor_text_color #241b2f

# Selection
selection_foreground #241b2f
selection_background #c084fc

# --- Normal colors ---
color0 #2b213a
color1 #c084fc
color2 #c084fc
color3 #c084fc
color4 #c084fc
color5 #d8b4ff
color6 #c084fc
color7 #e9d5ff

# --- Bright colors ---
color8 #4b3566
color9 #d8b4ff
color10 #d8b4ff
color11 #d8b4ff
color12 #d8b4ff
color13 #e879f9
color14 #f0abfc
color15 #faf5ff

# --- Cursor style ---
cursor_shape beam
cursor_blink_interval 0.5
